#!/usr/bin/env bash

# SET PWD TO DIRNAME OF THIS SCRIPT
# this script should always be located next to
# docker-compose.yml & the test_runner package
# directory (containing python env & tests)
current_dir=`dirname "$0"`
cd $current_dir
cd ..

# remove old backup
# backup current site files
# copy new build to site directory
# create pdf from live site
node ./scripts/generate-pdf.js
